<?php
const CFG_DEFAULT_LANG = "ru";
const CFG_ENABLE_REQUEST_SECURITY_SIGNATURE = false;
const CFG_BASE_SECURITY_TIME_FRAME = 60*5;
const CFG_ALLOWED_LANGUAGES = ["ru"];
const CFG_LOGS_FOLDER = __DIR__ . "/../../logs/";
const CFG_GENERAL_LOG = "aq";
const CFG_VERBOSE_MODE = 1;
const CFG_IOS_IN_APP_PASSWORD = "";
const CFG_ANDROID_CLIENT_ID = "";
const CFG_ANDROID_CLIENT_SECRET = "";
const CFG_ANDROID_REFRESH_TOKEN = "";
const CFG_FCM_SERVER_KEY = "";
const CFG_ANDROID_APPLICATION_ID = "";
