<?php
require_once __DIR__ . "/strings.php";

const ERR_DB_EXCEPTION = 100;
const ERR_CREATE_FOLDER = 200;
const ERR_BROKEN_REQUEST_CLASS = 300;
const ERR_AUTH_REQUIRED = 403;
const ERR_UNKNOWN_ACTION = 999;
const ERR_UNKNOWN = 1000;
const ERR_SECURITY_FAILED = 1101;
const ERR_AUTH_FAILED = 1100;
const ERR_WRONG_PASSWORD = 1102;
const ERR_VALIDATOR = 2000;
const ERR_VALIDATOR_ACCEPTED = 2001;
const ERR_VALIDATOR_ACCEPTED_IF = 2002;
const ERR_VALIDATOR_DECLINED = 20013;
const ERR_VALIDATOR_DECLINED_IF = 20023;
const ERR_VALIDATOR_ACTIVE_URL = 20021;
const ERR_VALIDATOR_ALPHA = 2007;
const ERR_VALIDATOR_ALPHA_DASH = 20071;
const ERR_VALIDATOR_ALPHA_SPACE = 20072;
const ERR_VALIDATOR_MIN = 2008;
const ERR_VALIDATOR_MIN_COUNT = 2009;
const ERR_VALIDATOR_MIN_NUMERIC = 2010;
const ERR_VALIDATOR_MIN_STRING = 2011;
const ERR_VALIDATOR_MIN_FILE = 20111;
const ERR_VALIDATOR_REQUIRED = 2012;
const ERR_VALIDATOR_STRING = 20100;
const ERR_VALIDATOR_ARRAY = 20101;
const ERR_VALIDATOR_ARRAY_FIELD = 20102;
const ERR_VALIDATOR_ARRAY_EXCESS = 20103;
const ERR_VALIDATOR_INTEGER = 20110;
const ERR_VALIDATOR_BOOLEAN = 20120;

const ERRORS = [
    ERR_UNKNOWN_ACTION         => [KEY_USER_MESSAGE => STR_ERR_UNKNOWN_ACTION],
    ERR_AUTH_REQUIRED          => [KEY_USER_MESSAGE => STR_ERR_AUTH_REQUIRED],
    ERR_AUTH_FAILED            => [KEY_USER_MESSAGE => STR_ERR_AUTH_FAILED],
    ERR_UNKNOWN                => [KEY_USER_MESSAGE => STR_ERR_UNKNOWN, KEY_IS_RECOVERABLE => 1],
    ERR_VALIDATOR              => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR],
    ERR_VALIDATOR_ACCEPTED     => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_ACCEPTED],
    ERR_VALIDATOR_ACCEPTED_IF  => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_ACCEPTED_IF],
    ERR_VALIDATOR_DECLINED     => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_DECLINED],
    ERR_VALIDATOR_DECLINED_IF  => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_DECLINED_IF],
    ERR_VALIDATOR_ACTIVE_URL   => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_ACTIVE_URL],
    ERR_VALIDATOR_ALPHA        => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_ALPHA],
    ERR_VALIDATOR_ALPHA_DASH   => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_ALPHA_DASH],
    ERR_VALIDATOR_ALPHA_SPACE  => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_ALPHA_SPACE],
    ERR_VALIDATOR_MIN          => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_MIN],
    ERR_VALIDATOR_MIN_COUNT    => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_MIN_COUNT],
    ERR_VALIDATOR_MIN_NUMERIC  => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_MIN_NUMERIC],
    ERR_VALIDATOR_MIN_STRING   => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_MIN_STRING],
    ERR_VALIDATOR_MIN_FILE     => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_MIN_FILE],
    ERR_VALIDATOR_REQUIRED     => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_REQUIRED],
    ERR_VALIDATOR_STRING       => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_STRING],
    ERR_VALIDATOR_ARRAY        => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_ARRAY],
    ERR_VALIDATOR_ARRAY_FIELD  => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_ARRAY_FIELD],
    ERR_VALIDATOR_ARRAY_EXCESS => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_ARRAY_EXCESS],
    ERR_VALIDATOR_INTEGER      => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_INTEGER],
    ERR_VALIDATOR_BOOLEAN      => [KEY_USER_MESSAGE => STR_ERR_VALIDATOR_BOOLEAN],
];
